version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=gestion-gym
    networks:
      - app_network

  frontend:
    build: .
    ports:
      - "5173:80"  # Ahora Nginx corre en el puerto 80 dentro del contenedor
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
